services:
    jgp_entity_list.list_factory:
        class: Jagilpe\EntityListBundle\EntityList\EntityListFactory

    # Twig Extension
    jgp_entity_list.twig_extension:
        class: Jagilpe\EntityListBundle\Twig\JagilpeEntityListExtension
        arguments:
            - "@twig"
            - "%jagilpe_components.lists_theme%"
        public: false
        tags:
            - { name: twig.extension }


    jgp_entity_list.single_field.column_type:
        class: Jagilpe\EntityListBundle\EntityList\ColumnType\SingleFieldColumnType
        arguments:
            - "@translator"
        public:     false
        tags:
            - { name: 'jgp_entity_list.column_type' }


    jgp_entity_list.datetime.column_type:
        class: Jagilpe\EntityListBundle\EntityList\ColumnType\DateTimeColumnType
        arguments:
            - "@translator"
        public:     false
        tags:
            - { name: 'jgp_entity_list.column_type' }